/*OC_PERSON QUERIES*/
SELECT * FROM OC_PERSON
SELECT * FROM OC_PERSON_HISTORY

/*EXEC INSERT_ROW_OC_PERSON @CNIC = 1644425695211, @FIRST_NAME = DAL, @LAST_NAME = HARVEY, @ADDRESS = '1133 Siice Court',	@AGE = 35,	@GENDER = M,	@DOB = '1978-02-16',	@NATIONALITY = SCOTTISH, @EMAIL = 'kus@vu.ai'*/

/*OC_PERSON_CONTACT QUERIES*/
SELECT * FROM OC_PERSON_CONTACT


/*OC_PATIENT QUERIES*/
SELECT * FROM OC_PATIENT


/*OC_DOCTOR QUERIES*/
SELECT * FROM OC_DOCTOR
SELECT * FROM OC_DOCTOR_HISTORY


/*OC_VISITS QUERIES*/
SELECT * FROM OC_VISITS


/*OC_MEDICINE QUERIES*/
SELECT * FROM OC_MEDICINE
SELECT * FROM OC_MEDICINE_HISTORY


/*OC_PERSCRIPTION QUERIES*/
SELECT * FROM OC_PERSCRIPTION


/*OC_RECEIPT QUERIES*/
SELECT * FROM OC_RECEIPT
SELECT * FROM OC_RECEIPT_DETAILS
