/*TABLE CREATION*/

CREATE SCHEMA CLINIC
GO
CREATE SCHEMA AUDIT
GO

CREATE TABLE CLINIC.[OC_PERSON] (
  [CNIC] NUMERIC(13) PRIMARY KEY,
  [FIRST_NAME] VARCHAR(30) NOT NULL,
  [LAST_NAME] VARCHAR(30) NOT NULL,
  [ADDRESS] VARCHAR(100) NOT NULL,
  [AGE] NUMERIC(2) NOT NULL,
  [GENDER] VARCHAR(1) NOT NULL,
  [DOB] DATE NOT NULL,
  [NATIONALITY] VARCHAR(10) NOT NULL,
  [EMAIL] VARCHAR(30) NOT NULL
)
GO

CREATE TABLE AUDIT.[OC_PERSON] (
  [SR_NO] NUMERIC IDENTITY(1,1),
  [CNIC] NUMERIC(13) NOT NULL,
  [FIRST_NAME] VARCHAR(30) NOT NULL,
  [LAST_NAME] VARCHAR(30) NOT NULL,
  [ADDRESS] VARCHAR(100) NOT NULL,
  [AGE] NUMERIC(2) NOT NULL,
  [GENDER] VARCHAR(1) NOT NULL,
  [DOB] DATE NOT NULL,
  [NATIONALITY] VARCHAR(10) NOT NULL,
  [EMAIL] VARCHAR(30) NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL,
  PRIMARY KEY ([SR_NO])
)
GO

CREATE TABLE CLINIC.[OC_PERSON_CONTACT] (
  [CNIC] NUMERIC(13),
  [SR_NO] NUMERIC,
  [CONTACT] NUMERIC(13),
  PRIMARY KEY ([CNIC], [SR_NO])
)
GO

CREATE TABLE AUDIT.[OC_PERSON_CONTACT] (
  SRR_NO NUMERIC IDENTITY(1,1),
  [CNIC] NUMERIC(13) NOT NULL,
  [SR_NO] NUMERIC NOT NULL,
  [CONTACT] NUMERIC(13) NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL,
  PRIMARY KEY ([SRR_NO])
)
GO

CREATE TABLE CLINIC.[OC_PATIENT] (
  [CNIC] NUMERIC(13) NOT NULL,
  [PAT_ID] NUMERIC  IDENTITY (1,1) PRIMARY KEY
)
GO

CREATE TABLE AUDIT.[OC_PATIENT] (
  SR_NO NUMERIC IDENTITY(1,1) PRIMARY KEY,
  [CNIC] NUMERIC(13) NOT NULL,
  [PAT_ID] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL,
)
GO

CREATE TABLE CLINIC.[OC_VISITS] (
  [VISIT_NO] NUMERIC,
  [PAT_ID] NUMERIC,
  [DOC_ID] NUMERIC,
  [PROBLEMS] NVARCHAR(MAX) NOT NULL,
  [DIAGNOSIS] NVARCHAR(MAX) NOT NULL,
  [VISIT_DATE] DATE NOT NULL,
  [VISIT_TIME] TIME NOT NULL,
  [FEE] NUMERIC NOT NULL
  PRIMARY KEY ([VISIT_NO], [PAT_ID], [DOC_ID])
)
GO

CREATE TABLE AUDIT.[OC_VISITS] (
  SR_NO NUMERIC IDENTITY(1,1) PRIMARY KEY,
  [VISIT_NO] NUMERIC NOT NULL,
  [PAT_ID] NUMERIC NOT NULL,
  [DOC_ID] NUMERIC NOT NULL,
  [PROBLEMS] NVARCHAR(MAX) NOT NULL,
  [DIAGNOSIS] NVARCHAR(MAX) NOT NULL,
  [VISIT_DATE] DATE NOT NULL,
  [VISIT_TIME] TIME NOT NULL,
  [FEE] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL
)
GO

CREATE TABLE CLINIC.[OC_DOCTOR] (
  [DOC_ID] NUMERIC IDENTITY(110001,1) PRIMARY KEY,
  [CNIC] NUMERIC(13) NOT NULL,
  [QUALIFICATION] NVARCHAR(MAX) NOT NULL,
  [SPECIALIZATION] NVARCHAR(MAX) NOT NULL,
  [FEE] NUMERIC NOT NULL
)
GO

CREATE TABLE AUDIT.[OC_DOCTOR] (
  [SR_NO] NUMERIC IDENTITY(1,1),
  [DOC_ID] NUMERIC NOT NULL,
  [CNIC] NUMERIC(13) NOT NULL,
  [QUALIFICATION] NVARCHAR(MAX) NOT NULL,
  [SPECIALIZATION] NVARCHAR(MAX) NOT NULL,
  [FEE] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL
  PRIMARY KEY ([SR_NO])
)
GO

CREATE TABLE CLINIC.[OC_MEDICINE] (
  [MED_ID] NUMERIC IDENTITY(1120000,1) PRIMARY KEY,
  [MED_NAME] VARCHAR(30) NOT NULL,
  [MED_POTENCY] VARCHAR(10) NOT NULL,
  [DESC] NVARCHAR(MAX) NOT NULL,
  [MGF_DATE] DATE NOT NULL,
  [EXP_DATE] DATE NOT NULL,
  [QUANTITY] NUMERIC NOT NULL,
  [PRICE] NUMERIC NOT NULL
)
GO

CREATE TABLE AUDIT.[OC_MEDICINE] (
  [SR_NO] NUMERIC IDENTITY(1,1),
  [MED_ID] NUMERIC NOT NULL,
  [MED_NAME] VARCHAR(30) NOT NULL,
  [MED_POTENCY] VARCHAR(10) NOT NULL,
  [DESC] NVARCHAR(MAX) NOT NULL,
  [MGF_DATE] DATE NOT NULL,
  [EXP_DATE] DATE NOT NULL,
  [QUANTITY] NUMERIC NOT NULL,
  [PRICE] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL,
  PRIMARY KEY ([SR_NO])
)
GO

CREATE TABLE CLINIC.[OC_PERSCRIPTION] (
  [PER_ID] NUMERIC,
  [VISIT_NO] NUMERIC,
  [PAT_ID] NUMERIC,
  [MED_ID] NUMERIC,
  [DOC_ID] NUMERIC NOT NULL,
  [QUANTITY] NUMERIC NOT NULL,
  PRIMARY KEY ([PER_ID], [VISIT_NO], [PAT_ID], [MED_ID])
)
GO

CREATE TABLE AUDIT.[OC_PERSCRIPTION] (
  SR_NO NUMERIC IDENTITY(1,1) PRIMARY KEY,
  [PER_ID] NUMERIC NOT NULL,
  [VISIT_NO] NUMERIC NOT NULL,
  [PAT_ID] NUMERIC NOT NULL,
  [MED_ID] NUMERIC NOT NULL,
  [DOC_ID] NUMERIC NOT NULL,
  [QUANTITY] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL
)
GO

CREATE TABLE CLINIC.[OC_RECEIPT] (
  [RECEIPT_NO] NUMERIC IDENTITY(1100001,1) PRIMARY KEY,
  [RECEIPT_DATE] DATE NOT NULL,
  [RECEIPT_TIME] TIME NOT NULL,
  [TOTAL_COST] NUMERIC NOT NULL
)
GO

CREATE TABLE AUDIT.[OC_RECEIPT] (
  SR_NO NUMERIC IDENTITY(1,1) PRIMARY KEY,
  [RECEIPT_NO] NUMERIC NOT NULL,
  [RECEIPT_DATE] DATE NOT NULL,
  [RECEIPT_TIME] TIME NOT NULL,
  [TOTAL_COST] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL  
)
GO

CREATE TABLE CLINIC.[OC_RECEIPT_DETAILS] (
  [RECEIPT_NO] NUMERIC,
  [PER_ID] NUMERIC,
  [VISIT_NO] NUMERIC,
  [PAT_ID] NUMERIC,
  [MED_ID] NUMERIC,
  [QUANTITY] NUMERIC NOT NULL,
  [TOTAL_COST] NUMERIC NOT NULL,
  PRIMARY KEY ([RECEIPT_NO], [PER_ID], [VISIT_NO], [PAT_ID], [MED_ID])
)
GO

CREATE TABLE AUDIT.[OC_RECEIPT_DETAILS] (
  SR_NO NUMERIC IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [RECEIPT_NO] NUMERIC NOT NULL,
  [PER_ID] NUMERIC NOT NULL,
  [VISIT_NO] NUMERIC NOT NULL,
  [PAT_ID] NUMERIC NOT NULL,
  [MED_ID] NUMERIC NOT NULL,
  [QUANTITY] NUMERIC NOT NULL,
  [TOTAL_COST] NUMERIC NOT NULL,
  EDIT_DATETIME DATETIME NOT NULL,
  OPERATION_TYPE NUMERIC(1) NOT NULL
)
GO

ALTER TABLE CLINIC.[OC_PERSON_CONTACT] ADD FOREIGN KEY ([CNIC]) REFERENCES CLINIC.[OC_PERSON] ([CNIC])
GO

ALTER TABLE CLINIC.[OC_PATIENT] ADD FOREIGN KEY ([CNIC]) REFERENCES CLINIC.[OC_PERSON] ([CNIC])
GO

ALTER TABLE CLINIC.[OC_VISITS] ADD FOREIGN KEY ([PAT_ID]) REFERENCES CLINIC.[OC_PATIENT] ([PAT_ID])
GO

ALTER TABLE CLINIC.[OC_VISITS] ADD FOREIGN KEY ([DOC_ID]) REFERENCES CLINIC.[OC_DOCTOR] ([DOC_ID])
GO

ALTER TABLE CLINIC.[OC_DOCTOR] ADD FOREIGN KEY ([CNIC]) REFERENCES CLINIC.[OC_PERSON] ([CNIC])
GO

ALTER TABLE CLINIC.[OC_PERSCRIPTION] ADD FOREIGN KEY ([VISIT_NO],[PAT_ID],[DOC_ID]) REFERENCES CLINIC.[OC_VISITS] ([VISIT_NO],[PAT_ID],[DOC_ID])
GO

ALTER TABLE CLINIC.[OC_PERSCRIPTION] ADD FOREIGN KEY ([MED_ID]) REFERENCES CLINIC.[OC_MEDICINE] ([MED_ID])
GO

ALTER TABLE CLINIC.[OC_RECEIPT_DETAILS] ADD FOREIGN KEY ([RECEIPT_NO]) REFERENCES CLINIC.[OC_RECEIPT] ([RECEIPT_NO])
GO

ALTER TABLE CLINIC.[OC_RECEIPT_DETAILS] ADD FOREIGN KEY ([PER_ID],[VISIT_NO],[PAT_ID],[MED_ID]) REFERENCES CLINIC.[OC_PERSCRIPTION] ([PER_ID],[VISIT_NO],[PAT_ID],[MED_ID])
GO

ALTER TABLE CLINIC.[OC_RECEIPT_DETAILS] ADD FOREIGN KEY ([MED_ID]) REFERENCES CLINIC.[OC_MEDICINE] ([MED_ID])
GO

/* TABLE DELETION */
DROP TABLE CLINIC.[OC_RECEIPT_DETAILS];
DROP TABLE AUDIT.[OC_RECEIPT_DETAILS];
DROP TABLE CLINIC.[OC_RECEIPT];
DROP TABLE AUDIT.[OC_RECEIPT];
DROP TABLE CLINIC.[OC_PERSCRIPTION];
DROP TABLE AUDIT.[OC_PERSCRIPTION];
DROP TABLE AUDIT.[OC_MEDICINE];
DROP TABLE CLINIC.[OC_MEDICINE];
DROP TABLE AUDIT.[OC_VISITS];
DROP TABLE CLINIC.[OC_VISITS];
DROP TABLE AUDIT.[OC_DOCTOR];
DROP TABLE CLINIC.[OC_DOCTOR];
DROP TABLE AUDIT.[OC_PATIENT];
DROP TABLE CLINIC.[OC_PATIENT];
DROP TABLE AUDIT.[OC_PERSON_CONTACT];
DROP TABLE CLINIC.[OC_PERSON_CONTACT];
DROP TABLE AUDIT.[OC_PERSON];
DROP TABLE CLINIC.[OC_PERSON];


/*SCHEMA DELETION*/
DROP SCHEMA CLINIC
DROP SCHEMA AUDIT