/*OC_PERSON QUERIES*/
SELECT * FROM CLINIC.OC_PERSON
SELECT * FROM AUDIT.OC_PERSON


/*OC_PERSON_CONTACT QUERIES*/
SELECT * FROM CLINIC.OC_PERSON_CONTACT
SELECT * FROM AUDIT.OC_PERSON_CONTACT


/*OC_PATIENT QUERIES*/
SELECT * FROM CLINIC.OC_PATIENT
SELECT * FROM AUDIT.OC_PATIENT


/*OC_DOCTOR QUERIES*/
SELECT * FROM CLINIC.OC_DOCTOR
SELECT * FROM AUDIT.OC_DOCTOR


/*OC_MEDICINE QUERIES*/
SELECT * FROM CLINIC.OC_MEDICINE
SELECT * FROM AUDIT.OC_MEDICINE


/*OC_VISITS QUERIES*/
SELECT * FROM CLINIC.OC_VISITS
SELECT * FROM AUDIT.OC_VISITS


/*OC_PERSCRIPTION QUERIES*/
SELECT * FROM CLINIC.OC_PERSCRIPTION
SELECT * FROM AUDIT.OC_PERSCRIPTION


/*OC_RECEIPT QUERIES*/
SELECT * FROM CLINIC.OC_RECEIPT
SELECT * FROM AUDIT.OC_RECEIPT


/*OC_RECEIPT_DETAILS QUERIES*/
SELECT * FROM CLINIC.OC_RECEIPT_DETAILS
SELECT * FROM AUDIT.OC_RECEIPT_DETAILS


/*REPORTS*/

/*1*/
SELECT 
	DOC_ID AS 'Doctor ID', 
	COUNT(PAT_ID) AS 'Total patients examined' 
FROM CLINIC.OC_VISITS 
GROUP BY DOC_ID


/*2*/
SELECT PAT_ID AS 'Patient ID', 
	SUM(FEE) AS 'Total Fee paid' 
FROM CLINIC.OC_VISITS 
GROUP BY PAT_ID

SELECT OCRD.PAT_ID, 
	SUM(DISTINCT OCRD.TOTAL_COST)
FROM CLINIC.OC_RECEIPT_DETAILS OCRD
GROUP BY OCRD.PAT_ID


/*3*/
SELECT OCRD.PAT_ID AS 'Patient ID', 
	SUM(DISTINCT OCR.TOTAL_COST) 'Total Amount paid'
FROM CLINIC.OC_RECEIPT OCR,
	CLINIC.OC_RECEIPT_DETAILS OCRD
WHERE OCR.RECEIPT_NO IN (SELECT RECEIPT_NO FROM CLINIC.OC_RECEIPT_DETAILS WHERE PAT_ID = OCRD.PAT_ID GROUP BY RECEIPT_NO)
GROUP BY OCRD.PAT_ID


/*4*/
SELECT TOP 3 OCRD.PAT_ID AS 'Patient ID', 
	SUM(DISTINCT OCR.TOTAL_COST) 'Total Amount paid'
FROM CLINIC.OC_RECEIPT OCR,
	CLINIC.OC_RECEIPT_DETAILS OCRD
WHERE OCR.RECEIPT_NO IN (SELECT RECEIPT_NO FROM CLINIC.OC_RECEIPT_DETAILS WHERE PAT_ID = OCRD.PAT_ID GROUP BY RECEIPT_NO)
GROUP BY OCRD.PAT_ID
ORDER BY SUM(DISTINCT OCR.TOTAL_COST) DESC


/*5*/